apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-api
  template:
    metadata:
      labels:
        app: go-demo-api
    spec:
      containers:
      - name: go-demo-api
        image: somkiat/go-demo-api
        imagePullPolicy: Always
        ports:
            - containerPort: 8080